# This is a basic workflow to help you get started with Actions

name: PHP Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master
        
      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master
        
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
      
      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master
